// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// lagAvgTopN
NumericVector lagAvgTopN(NumericVector values, NumericVector endDates, int n, int window, NumericVector adj);
RcppExport SEXP _statskier2_lagAvgTopN(SEXP valuesSEXP, SEXP endDatesSEXP, SEXP nSEXP, SEXP windowSEXP, SEXP adjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endDates(endDatesSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adj(adjSEXP);
    rcpp_result_gen = Rcpp::wrap(lagAvgTopN(values, endDates, n, window, adj));
    return rcpp_result_gen;
END_RCPP
}
// ptsThresh
NumericVector ptsThresh(NumericVector values, NumericVector endDates, int window);
RcppExport SEXP _statskier2_ptsThresh(SEXP valuesSEXP, SEXP endDatesSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endDates(endDatesSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(ptsThresh(values, endDates, window));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_statskier2_lagAvgTopN", (DL_FUNC) &_statskier2_lagAvgTopN, 5},
    {"_statskier2_ptsThresh", (DL_FUNC) &_statskier2_ptsThresh, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_statskier2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
