# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lagAvgTopN <- function(values, endDates, n, window, adj) {
    .Call('_statskier2_lagAvgTopN', PACKAGE = 'statskier2', values, endDates, n, window, adj)
}

lagMedianAll <- function(values, endDates, window, adj) {
    .Call('_statskier2_lagMedianAll', PACKAGE = 'statskier2', values, endDates, window, adj)
}

lagMAD <- function(values, endDates, window) {
    .Call('_statskier2_lagMAD', PACKAGE = 'statskier2', values, endDates, window)
}

lagSD <- function(values, endDates, window) {
    .Call('_statskier2_lagSD', PACKAGE = 'statskier2', values, endDates, window)
}

ptsThresh <- function(values, endDates, window) {
    .Call('_statskier2_ptsThresh', PACKAGE = 'statskier2', values, endDates, window)
}

